name: inka
description: MVP App de Tatuajes con AR
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Cámara y Permisos
  camera: ^0.10.5
  permission_handler: ^11.0.0
  # Inteligencia Artificial
  google_mlkit_pose_detection: ^0.10.0
  supabase_flutter: ^2.12.0
  image_picker: ^1.2.1
  http: ^1.6.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
  assets:
    - assets/images/ # <--- IMPORTANTE: Crea esta carpeta y pon ahí un 'tattoo.png'